services:
  - type: web
    name: product-inventory-api
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
